### ISSUE TITLE
Project progress

### ISSUE THREAD

**Issue by EnzoFranzini1** [EnzoFranzini1/video_creator#1]
**TODO**

---

- [ ] **Main controller**
  - [x] Ask for the search term
  - [x] Ask for the prefix 
  - [x] Start text bot
  - [x] Start image bot
  - [x] Start video bot
  - [ ] Start You Tube bot

---

- [x] **Text bot**
  - [x] Data structure
  - [x] Get Wikipedia content
  - [x] Clean up content
  - [x] Break sentences
  - [x] Get Watson informations
  - [x] Add tags
  - [x] Save data structure

---
  
- [x] **Image bot**
  - [x] Load data structure
  - [x] Search images in Google Images
  - [x] Download the images
  - [x] Save data structure

---

- [ ] **Video bot**
  - [x] Handle the images
  - [x] Create sentences with images
  - [x] Create the video thumbnail
  - [ ] Render the video using After Effects

---

- [ ] **You Tube bot**
  - [ ] Authenticate with OAuth
  - [ ] Upload video
  - [ ] Upload thumbnail
